name: CI-CD-pipeline-aws

env:
 EB_PACKAGE_S3_BUCKET_NAME: "elasticbeanstalk-eu-north-1-848908255870E"
 EB_APPLICATION_NAME: "MYFLASK"
 EB_ENVIRONMENT_NAME: "FLASK-ENV"
 DEPLOY_PACKAGE_NAME: "flask_app_${{ github.sha }}.zip"
 AWS_REGION_NAME: "eu-north-1"


on:
   push:
    branches:
      - main


jobs:
  ci-pipeline:
      runs-on: ubuntu-latest
      steps:
      - name: Git clone repo
        uses: actions/checkout@v3

        
      - name: Create zip deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

        
      - name: Config AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_KEY }} 
          aws-region: ${{ env.AWS_REGION_NAME }}

          
      - name: Copy package to S3 Bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      
     
